name: weeklyreport

on:
  schedule:
    - cron: '0 15 * * 2'  # Runs at 01:00 AEST Wednesday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright

    - name: Run script
      run: python price_checker.py