name: weeklyreport

on:
  schedule:
    - cron: '0 15 * * 2'  # Runs at 01:00 AEST Wednesday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Firefox for Playwright
        run: npx playwright install firefox

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "pymongo[srv]"
          pip install requests playwright

      - name: Run MongoDB script
        env:
          MONGO_KEY: ${{ secrets.MONGO_KEY }}
        run: python mongodb_script.py

      - name: Run Price Checker script
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASS: ${{ secrets.USER_PASS }}
        run: python price_checker.py